# Generated by Django 5.2.6 on 2025-09-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="queue_position",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
