# Generated by Django 5.2.6 on 2026-04-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_is_main_player_queue_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_players_limit', models.PositiveIntegerField(default=20)),
            ],
        ),
    ]
