# Generated by Django 5.2.6 on 2026-04-27 16:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_gameconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameconfig',
            name='racha_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('210.00'), max_digits=8),
        ),
    ]
