# Generated by Django 5.2.6 on 2026-09-19 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_vote_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed_on', models.DateField(unique=True)),
                ('total_players', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-closed_on'],
            },
        ),
        migrations.CreateModel(
            name='RoundResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField()),
                ('average_rank', models.FloatField(blank=True, null=True)),
                ('voting_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='players.votinground')),
            ],
            options={
                'ordering': ['position', 'player_name'],
                'unique_together': {('voting_round', 'player_name')},
            },
        ),
    ]
