# Generated by Django 5.2.6 on 2026-09-19 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_votinground_roundresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameconfig',
            name='hide_racha_value',
        ),
        migrations.RemoveField(
            model_name='gameconfig',
            name='main_players_limit',
        ),
        migrations.RemoveField(
            model_name='gameconfig',
            name='racha_value',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_main',
        ),
        migrations.RemoveField(
            model_name='player',
            name='queue_position',
        ),
    ]
